# Generated by Django 4.2.7 on 2025-07-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_type', models.CharField(max_length=50)),
                ('review', models.IntegerField()),
            ],
        ),
    ]
